import React, { useMemo, useRef, useEffect } from 'react';
import { ChatMessage } from '../types';
import { User, Bot, Copy, Download, Check, Globe, X, Pencil } from 'lucide-react';
import { marked } from 'marked';
import { jsPDF } from 'jspdf';
import { motion, AnimatePresence } from 'motion/react';

interface MessageBubbleProps {
  message: ChatMessage;
  onEdit?: (text: string) => void;
}

export const MessageBubble: React.FC<MessageBubbleProps> = ({ message, onEdit }) => {
  const isUser = message.role === 'user';
  const [copied, setCopied] = React.useState(false);
  const dialogRef = useRef<HTMLDialogElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  const htmlContent = useMemo(() => {
    if (!message.content) return '';

    const renderer = new marked.Renderer();

    renderer.code = (code, language) => {
      const validLang = language || 'plaintext';
      return `<div class="code-block-container" data-language="${validLang}"><pre><code class="language-${validLang}">${code}</code></pre></div>`;
    };

    try {
      return marked.parse(message.content, { 
        renderer, 
        breaks: true, 
        gfm: true
      }) as string;
    } catch (e) {
      console.error("Markdown parsing error:", e);
      return message.content; 
    }
  }, [message.content]);

  useEffect(() => {
    if (!contentRef.current) return;

    const containers = contentRef.current.querySelectorAll('.code-block-container');
    containers.forEach(container => {
      if (container.querySelector('.code-header')) return;

      const lang = container.getAttribute('data-language') || 'text';
      const codeElement = container.querySelector('code');
      const codeText = codeElement?.textContent || '';

      const header = document.createElement('div');
      header.className = 'code-header flex items-center justify-between px-4 py-2 bg-gray-800 rounded-t-lg border-b border-gray-700';
      header.innerHTML = `
        <span class="text-xs font-mono font-bold text-gray-400 uppercase">${lang}</span>
        <button class="copy-btn flex items-center gap-1.5 text-xs text-gray-400 hover:text-white transition-colors">
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>
          Copy
        </button>
      `;

      const pre = container.querySelector('pre');
      if (pre) {
        pre.className = 'm-0 p-4 bg-gray-950 overflow-x-auto rounded-b-lg text-sm font-mono';
      }

      const btn = header.querySelector('.copy-btn');
      btn?.addEventListener('click', async () => {
        try {
          await navigator.clipboard.writeText(codeText);
          btn.innerHTML = `<span class="text-green-400">Copied!</span>`;
          setTimeout(() => {
            btn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg> Copy`;
          }, 2000);
        } catch (err) {}
      });

      container.insertBefore(header, pre);
      container.className = 'my-4 rounded-lg border border-gray-700 bg-gray-950 shadow-md overflow-hidden';
    });

  }, [htmlContent]);

  const handleCopy = () => {
    if (!message.content) return;
    navigator.clipboard.writeText(message.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text("AI Assistant Response", 10, 15);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by AI Assistant`, 10, 20);
    doc.setFontSize(12);
    doc.setTextColor(0);
    const splitText = doc.splitTextToSize(message.content, 180);
    doc.text(splitText, 10, 30);
    doc.save(`ai_response.pdf`);
  };

  const hasSources = message.groundingChunks && message.groundingChunks.length > 0;
  const isThinking = !isUser && !message.isComplete && !message.content;

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="w-full mb-8"
    >
      <div className="flex flex-col gap-2">
        <h3 className={`text-sm font-bold uppercase tracking-wider flex items-center gap-2 ${isUser ? 'text-primary' : 'text-emerald-400'}`}>
          {isUser ? <><User size={16} /> User</> : <><Bot size={16} /> AI Assistant</>}
        </h3>

        <div className={`relative rounded-xl p-6 shadow-sm border ${isUser ? 'bg-surface border-gray-700/50 text-gray-100' : 'bg-background border-emerald-900/30 text-gray-100'}`}>
          {isThinking ? (
             <div className="flex items-center gap-1 h-6 py-1" role="status" aria-label="AI is thinking">
              <span className="text-sm text-gray-400 mr-2 font-medium animate-pulse">Processing</span>
              <div className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
              <div className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-bounce [animation-delay:-0.15s]"></div>
              <div className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-bounce"></div>
            </div>
          ) : isUser ? (
            <p className="whitespace-pre-wrap leading-relaxed text-base">{message.content}</p>
          ) : (
            <>
              <div 
                ref={contentRef}
                className="markdown-content max-w-none text-base leading-relaxed break-words"
                dangerouslySetInnerHTML={{ __html: htmlContent }} 
              />
              {!message.isComplete && <span className="inline-block w-2 h-4 ml-1 bg-emerald-400 animate-pulse align-middle" />}
            </>
          )}

          {(isUser || (message.isComplete && message.content)) && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.2 }}
              className="flex flex-wrap items-center gap-2 mt-4 pt-4 border-t border-gray-700/30"
            >
              <motion.button 
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={handleCopy} 
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-gray-800 hover:bg-gray-700 text-xs text-gray-300 transition-colors border border-gray-700"
              >
                {copied ? <Check size={12} className="text-green-400" /> : <Copy size={12} />}
                {copied ? 'Copied' : 'Copy'}
              </motion.button>

              {isUser && onEdit && (
                <motion.button 
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={() => onEdit(message.content)} 
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-gray-800 hover:bg-gray-700 text-xs text-gray-300 transition-colors border border-gray-700"
                >
                  <Pencil size={12} />
                  Edit
                </motion.button>
              )}

              {!isUser && message.content && (
                <motion.button 
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={handleExport} 
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-emerald-900/30 hover:bg-emerald-900/50 text-xs text-emerald-400 transition-colors border border-emerald-900/50"
                >
                  <Download size={12} /> Export
                </motion.button>
              )}

              {!isUser && hasSources && (
                <>
                  <motion.button 
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    onClick={() => dialogRef.current?.showModal()} 
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-blue-900/30 hover:bg-blue-900/50 text-xs text-blue-400 transition-colors border border-blue-900/50"
                  >
                    <Globe size={12} /> Sources ({message.groundingChunks?.length})
                  </motion.button>
                  <dialog ref={dialogRef} className="bg-surface text-gray-100 p-0 rounded-xl border border-gray-700 shadow-2xl backdrop:bg-black/80 max-w-lg w-full m-auto">
                    <div className="p-4 border-b border-gray-700 flex justify-between items-center bg-gray-900/50">
                      <h4 className="font-bold flex items-center gap-2 text-sm"><Globe size={16} className="text-blue-400"/> Search Sources</h4>
                      <motion.button 
                        whileHover={{ scale: 1.1 }}
                        whileTap={{ scale: 0.9 }}
                        onClick={() => dialogRef.current?.close()} 
                        className="text-gray-400 hover:text-white"
                      >
                        <X size={18} />
                      </motion.button>
                    </div>
                    <div className="p-4 max-h-[60vh] overflow-y-auto space-y-3">
                      {message.groundingChunks?.map((chunk, i) => chunk.web ? (
                        <div key={i} className="bg-background p-3 rounded-lg border border-gray-700 hover:border-blue-500/50 transition-colors">
                          <a href={chunk.web.uri} target="_blank" rel="noopener noreferrer" className="block">
                            <div className="text-sm font-medium text-blue-300 mb-1 hover:underline truncate">{chunk.web.title}</div>
                            <div className="text-xs text-gray-500 truncate font-mono">{chunk.web.uri}</div>
                          </a>
                        </div>
                      ) : null)}
                    </div>
                  </dialog>
                </>
              )}
            </motion.div>
          )}
        </div>
      </div>
    </motion.div>
  );
};